
development:
  stripe_publishable_key: pk_test_pUFkdQjBPOvTswhElBfiCXPH
  stripe_secret_key: sk_test_rcHcPOtgSwy9sJgo0HXDWnxS


production:
  stripe_publishable_key: pk_test_pUFkdQjBPOvTswhElBfiCXPH
  stripe_secret_key: sk_test_rcHcPOtgSwy9sJgo0HXDWnxS